#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 100.
fine=1
while [ $fine -ne 101 ]
do
    if [ $((fine % 15)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((fine % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((fine % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
	echo $fine
    fi
    fine=$((fine + 1))
done
