#!/usr/bin/env bash
#display process and PID file

file="/var/run/myscript.pid"
echo $$ >"$file"

#handles signals
trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT

while :; do
	echo "to infinity and beyond"
	sleep 2
done
